// <auto-generated>
// MIT
// </auto-generated>

namespace Haipa.ComputeClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OperationResource
    {
        /// <summary>
        /// Initializes a new instance of the OperationResource class.
        /// </summary>
        public OperationResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OperationResource class.
        /// </summary>
        /// <param name="resourceType">Possible values include:
        /// 'Machine'</param>
        public OperationResource(System.Guid? id = default(System.Guid?), System.Guid? resourceId = default(System.Guid?), string resourceType = default(string), Operation operation = default(Operation))
        {
            Id = id;
            ResourceId = resourceId;
            ResourceType = resourceType;
            Operation = operation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceId")]
        public System.Guid? ResourceId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Machine'
        /// </summary>
        [JsonProperty(PropertyName = "resourceType")]
        public string ResourceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operation")]
        public Operation Operation { get; set; }

    }
}
