// <auto-generated>
// MIT
// </auto-generated>

namespace Haipa.ClientRuntime
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OperationLogEntry
    {
        /// <summary>
        /// Initializes a new instance of the OperationLogEntry class.
        /// </summary>
        public OperationLogEntry()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OperationLogEntry class.
        /// </summary>
        public OperationLogEntry(System.Guid? id = default(System.Guid?), string message = default(string), System.DateTime? timestamp = default(System.DateTime?))
        {
            Id = id;
            Message = message;
            Timestamp = timestamp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime? Timestamp { get; set; }

    }
}
