// <auto-generated>
// MIT
// </auto-generated>

namespace Haipa.ClientRuntime
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Operation
    {
        /// <summary>
        /// Initializes a new instance of the Operation class.
        /// </summary>
        public Operation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Operation class.
        /// </summary>
        /// <param name="status">Possible values include: 'Queued', 'Running',
        /// 'Failed', 'Completed'</param>
        public Operation(string id = default(string), string status = default(string), string statusMessage = default(string), IList<OperationResource> resources = default(IList<OperationResource>), IList<OperationLogEntry> logEntries = default(IList<OperationLogEntry>))
        {
            Id = id;
            Status = status;
            StatusMessage = statusMessage;
            Resources = resources;
            LogEntries = logEntries;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Queued', 'Running',
        /// 'Failed', 'Completed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusMessage")]
        public string StatusMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resources")]
        public IList<OperationResource> Resources { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logEntries")]
        public IList<OperationLogEntry> LogEntries { get; set; }

    }
}
